services:
  ruslo-app:
    depends_on:
      - db
    build:
      context: ./bm-application
    container_name: blimfy
    ports:
      - "8080:8080"
    networks:
      - ruslo_network
    command:
      - java
      - -jar
      - ruslo.jar
    environment:
      RUSLO_FULL_DEBUG: true
      RUSLO_DB_HOST: db

  ruslo-db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ruslo_admin
      POSTGRES_PASSWORD: ruslo_password
      POSTGRES_DB: ruslo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ruslo_network

volumes:
  db_data:

networks:
  ruslo_network:
    driver: bridge
