services:
  microservice:
    container_name: gateway-microservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHANNEL_SERVICE_CLIENT_URL: http://localhost:8081
      SERVER_SERVICE_CLIENT_URL: http://localhost:8083
      USER_SERVICE_CLIENT_URL: http://localhost:8084
    ports:
      - "8082:8080"
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge