bm-security:
  jwt:
    issuer: ${BM_SECURITY_JWT_ISSUER:Blimfy}
    key: ${BM_SECURITY_JWT_KEY:secret_key_is_very_well_and_good}
  permitAllPaths:
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/v1/auth/sign-up"
    - "/v1/auth/sign-in"