[versions]
springBoot = "3.5.6"
kotlin = "2.2.20"
jwt = "0.13.0"
springDoc = "2.8.13"

[libraries]
# Spring Boot.
springBootStarterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springBootStarterIntegration = { module = "org.springframework.boot:spring-boot-starter-integration" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarter = { module = "org.springframework.boot:spring-boot-starter" }

# Документация.
springDocWebflux = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springDoc" }

# Безопасность.
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
springSecurityCore = { module = "org.springframework.security:spring-security-core" }
jwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jwt" }
jwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jwt" }

# Работа с базой данных.
springBootStarterDataR2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
springDataCommons = { module = "org.springframework.data:spring-data-commons" }
databasePostgresR2dbc = { module = "org.postgresql:r2dbc-postgresql" }
databasePostgres = { module = "org.postgresql:postgresql" }
liquibaseCore = { module = "org.liquibase:liquibase-core" }
hikari = { module = "com.zaxxer:HikariCP" }

# Работа с JSON.
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind" }

# Котлин.
kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Тесты.
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }
testcontainersPostgres = { module = "org.testcontainers:postgresql" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }