[versions]
springBoot = "3.4.5"
kotlin = "2.1.20"
dependencyManagement = "1.1.7"
jwt = "0.12.6"
springDoc = "2.8.6"

[libraries]
# Spring Boot.
springBootStarterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springBootStarterIntegration = { module = "org.springframework.boot:spring-boot-starter-integration" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }

# Документация.
springDocWebflux = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springDoc" }

# Безопасность.
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
jwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jwt" }
jwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jwt" }

# Работа с базой данных.
springBootStarterDataR2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
databasePostgresR2dbc = { module = "org.postgresql:r2dbc-postgresql" }

# Сериализация (например, для дат).
jacksonJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# Котлин.
kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinReactorExtension = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Тесты.
springBooStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }
mockito = { module = "org.mockito:mockito-core" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }