[versions]
springBoot = "3.4.5"
kotlin = "2.1.20"
jwt = "0.12.6"
springDoc = "2.8.8"

[libraries]
# Spring Boot.
springBootStarterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springBootStarterIntegration = { module = "org.springframework.boot:spring-boot-starter-integration" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarter = { module = "org.springframework.boot:spring-boot-starter" }

# Spring.
springCore = { module = "org.springframework:spring-core" }
springBeans = { module = "org.springframework:spring-beans" }

# Документация.
springDocWebflux = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springDoc" }

# Безопасность.
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
jwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jwt" }
jwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jwt" }

# Работа с базой данных.
springBootStarterDataR2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
databasePostgresR2dbc = { module = "org.postgresql:r2dbc-postgresql" }
databasePostgres = { module = "org.postgresql:postgresql" }
liquibaseCore = { module = "org.liquibase:liquibase-core" }
hikari = { module = "com.zaxxer:HikariCP" }

# Сериализация (например, для дат).
jacksonJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# Котлин.
kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Тесты.
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }
testcontainersPostgres = { module = "org.testcontainers:postgresql" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }