services:
  postgres:
    container_name: server-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: server_service
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - server_network

  microservice:
    container_name: server-microservice
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_DB_HOST: server-postgres
      SERVICE_DB_PORT: 5432
    ports:
      - "8083:8080"
    networks:
      - server_network

volumes:
  postgres_data:

networks:
  server_network:
    driver: bridge