# Количество логов. При "true" будет отображено больше логов.
debug: ${BM_FULL_DEBUG:false}

# Логирование запросов к БД.
logging:
  level:
    ru:
      blimfy: ${BM_LOGGING_LEVEL:debug}
    org:
      springframework:
        # Логирование SQL запросов.
        r2dbc: ${BM_LOGGING_LEVEL_R2DBC:debug}
    io:
      r2dbc:
        postgresql:
          # Логирование параметров SQL запросов.
          PARAM: ${BM_LOGGING_LEVEL_R2DBC:debug}

spring:
  # Настройки реактивности.
  webflux:
    base-path: /blimfy

  # Общие настройки Spring.
  main:
    # Выключить баннер в логах.
    banner-mode: off
    # Уменьшение количества начальных логов.
    log-startup-info: false

  # Настройки версионирования БД.
  liquibase:
    show-summary: off