services:
  postgres:
    container_name: user-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_service
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - user_network

  microservice:
    container_name: user-microservice
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_DB_HOST: user-postgres
      SERVICE_DB_PORT: 5432
    ports:
      - "8084:8080"
    networks:
      - user_network

volumes:
  postgres_data:

networks:
  user_network:
    driver: bridge